# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
# source file: approvals.sql
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "PendingApprovalsRow",
    "QueryResults",
    "approve_pr",
    "drop_pending_approval",
    "gate_pr",
    "pending_approvals",
    "pr_approved",
)

import dataclasses
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc
    import datetime

    type QueryResultsArgsType = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[QueryResultsArgsType] | None

    type ConnectionLike = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]


@dataclasses.dataclass()
class PendingApprovalsRow:
    pr_number: int
    pr_author: str
    commit_sha: str
    created_at: datetime.datetime


PR_APPROVED: typing.Final[str] = """-- name: PrApproved :one
SELECT 1 AS approved FROM pr_approvals
WHERE project_id = $1 AND pr_number = $2 AND approved_at IS NOT NULL
"""

GATE_PR: typing.Final[str] = """-- name: GatePr :exec
INSERT INTO pr_approvals (project_id, pr_number, pending)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, pr_number) DO UPDATE
SET pending = EXCLUDED.pending, created_at = now()
"""

APPROVE_PR: typing.Final[str] = """-- name: ApprovePr :one
WITH held AS (
    SELECT h.pending FROM pr_approvals h
    WHERE h.project_id = $1 AND h.pr_number = $2 FOR UPDATE
), up AS (
    INSERT INTO pr_approvals (project_id, pr_number, approved_by, approved_at)
    VALUES ($1, $2, $3::text, now())
    ON CONFLICT (project_id, pr_number) DO UPDATE
    SET approved_by = EXCLUDED.approved_by,
        approved_at = COALESCE(pr_approvals.approved_at, EXCLUDED.approved_at),
        pending = NULL
)
SELECT pending FROM held
"""

PENDING_APPROVALS: typing.Final[str] = """-- name: PendingApprovals :many
SELECT pr_number,
       (pending->>'pr_author')::text AS pr_author,
       (pending->>'commit_sha')::text AS commit_sha,
       created_at
FROM pr_approvals
WHERE project_id = $1 AND approved_at IS NULL AND pending IS NOT NULL
ORDER BY created_at DESC
"""

DROP_PENDING_APPROVAL: typing.Final[str] = """-- name: DropPendingApproval :exec
DELETE FROM pr_approvals
WHERE project_id = $1 AND pr_number = $2 AND approved_at IS NULL
"""


class QueryResults[T]:
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]

        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def pr_approved(conn: ConnectionLike, *, project_id: int, pr_number: int) -> int | None:
    row = await conn.fetchrow(PR_APPROVED, project_id, pr_number)
    if row is None:
        return None
    return row[0]


async def gate_pr(conn: ConnectionLike, *, project_id: int, pr_number: int, pending: str | None) -> None:
    await conn.execute(GATE_PR, project_id, pr_number, pending)


async def approve_pr(conn: ConnectionLike, *, project_id: int, pr_number: int, approved_by: str | None) -> str | None:
    row = await conn.fetchrow(APPROVE_PR, project_id, pr_number, approved_by)
    if row is None:
        return None
    return row[0]


def pending_approvals(conn: ConnectionLike, *, project_id: int) -> QueryResults[PendingApprovalsRow]:
    def _decode_hook(row: asyncpg.Record) -> PendingApprovalsRow:
        return PendingApprovalsRow(pr_number=row[0], pr_author=row[1], commit_sha=row[2], created_at=row[3])

    return QueryResults(conn, PENDING_APPROVALS, _decode_hook, project_id)


async def drop_pending_approval(conn: ConnectionLike, *, project_id: int, pr_number: int) -> None:
    await conn.execute(DROP_PENDING_APPROVAL, project_id, pr_number)
