# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
# source file: builds.sql
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "AttributeStatusesRow",
    "EffectDepStatusesRow",
    "EffectsSummaryRow",
    "EvalJobRowsRow",
    "LockBuildRowRow",
    "QueryResults",
    "attach_build_to_pr",
    "attribute_status_list",
    "attribute_statuses",
    "backfill_pr_author",
    "bump_build_status",
    "complete_attribute",
    "create_build",
    "create_failed_build",
    "detach_build_from_pr",
    "effect_dep_statuses",
    "effects_for_build",
    "effects_summary",
    "eval_job_rows",
    "find_completed_eval",
    "find_reusable_build",
    "finish_effect",
    "get_build",
    "lock_build_identity",
    "lock_build_row",
    "mark_attribute_building",
    "mark_effects_started",
    "record_attributes",
    "record_skipped_effects",
    "set_build_status",
    "set_eval_warnings",
    "settle_unfinished_attributes",
    "start_effect",
    "start_pending_effects",
)

import dataclasses
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc
    import datetime

    type QueryResultsArgsType = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[QueryResultsArgsType] | None

    type ConnectionLike = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from nixbot.db_gen import models


@dataclasses.dataclass()
class EvalJobRowsRow:
    attr: str
    system: str | None
    drv_path: str | None
    outputs: str | None


@dataclasses.dataclass()
class EffectDepStatusesRow:
    name: str
    status: str


@dataclasses.dataclass()
class EffectsSummaryRow:
    failed: int
    succeeded: int
    status: str


@dataclasses.dataclass()
class AttributeStatusesRow:
    attr: str
    status: str


@dataclasses.dataclass()
class LockBuildRowRow:
    id_: int
    status: str
    status_generation: int


LOCK_BUILD_IDENTITY: typing.Final[str] = """-- name: LockBuildIdentity :exec

SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
"""

FIND_REUSABLE_BUILD: typing.Final[str] = """-- name: FindReusableBuild :one
SELECT id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_duration_ms, actor, merged_pr_number FROM builds WHERE project_id = $1 AND tree_hash = $2
AND status <> 'cancelled' ORDER BY id DESC LIMIT 1
"""

DETACH_BUILD_FROM_PR: typing.Final[str] = """-- name: DetachBuildFromPr :one
UPDATE builds SET pr_number = NULL, pr_author = NULL,
    merged_pr_number = CASE WHEN $2::bigint IS NULL
             THEN builds.pr_number ELSE NULL END,
    branch = CASE WHEN $2::bigint IS NULL
             THEN $3 ELSE branch END
WHERE id = $1 RETURNING id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_duration_ms, actor, merged_pr_number
"""

ATTACH_BUILD_TO_PR: typing.Final[str] = """-- name: AttachBuildToPr :one
UPDATE builds SET pr_number = $2, pr_author = $3 WHERE id = $1 RETURNING id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_duration_ms, actor, merged_pr_number
"""

BACKFILL_PR_AUTHOR: typing.Final[str] = """-- name: BackfillPrAuthor :one
UPDATE builds SET pr_author = $2 WHERE id = $1 RETURNING id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_duration_ms, actor, merged_pr_number
"""

CREATE_BUILD: typing.Final[str] = """-- name: CreateBuild :one
WITH n AS (
    UPDATE projects SET next_build_number = next_build_number + 1
    WHERE id = $1::bigint
    RETURNING next_build_number - 1 AS number
)
INSERT INTO builds (project_id, number, tree_hash, commit_sha,
                    branch, pr_number, pr_author, actor)
SELECT $1::bigint, n.number, $2::text,
       $3::text, $4::text,
       $5::bigint, $6::text,
       $7::text
FROM n
RETURNING id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_duration_ms, actor, merged_pr_number
"""

CREATE_FAILED_BUILD: typing.Final[str] = """-- name: CreateFailedBuild :one
WITH n AS (
    UPDATE projects SET next_build_number = next_build_number + 1
    WHERE id = $1::bigint
    RETURNING next_build_number - 1 AS number
)
INSERT INTO builds (project_id, number, commit_sha, branch,
                    pr_number, pr_author, status, error, finished_at)
SELECT $1::bigint, n.number, $2::text,
       $3::text, $4::bigint,
       $5::text, 'failed', $6::text, now()
FROM n
RETURNING id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_duration_ms, actor, merged_pr_number
"""

RECORD_ATTRIBUTES: typing.Final[str] = """-- name: RecordAttributes :exec
INSERT INTO build_attributes (build_id, attr, system, drv_path, outputs,
    eval_warnings, eval_wall_ms, eval_alloc_bytes, status)
SELECT $1::bigint, u.attr, u.system, u.drv_path, u.outputs,
    NULLIF(u.eval_warnings, 'null'::jsonb), NULLIF(u.eval_wall_ms, -1), NULLIF(u.eval_alloc_bytes, -1), 'pending'
FROM (SELECT unnest($2::text[]) AS attr,
             unnest($3::text[]) AS system,
             unnest($4::text[]) AS drv_path,
             unnest($5::jsonb[]) AS outputs,
             unnest($6::jsonb[]) AS eval_warnings,
             unnest($7::int[]) AS eval_wall_ms,
             unnest($8::bigint[]) AS eval_alloc_bytes) u
ON CONFLICT (build_id, attr) DO UPDATE SET
    system = EXCLUDED.system,
    drv_path = EXCLUDED.drv_path,
    outputs = EXCLUDED.outputs,
    eval_warnings = EXCLUDED.eval_warnings,
    eval_wall_ms = EXCLUDED.eval_wall_ms,
    eval_alloc_bytes = EXCLUDED.eval_alloc_bytes
WHERE build_attributes.status IN ('pending', 'building')
"""

SET_EVAL_WARNINGS: typing.Final[str] = """-- name: SetEvalWarnings :exec
UPDATE builds SET eval_warnings = $2::jsonb WHERE id = $1
"""

SET_BUILD_STATUS: typing.Final[str] = """-- name: SetBuildStatus :exec
WITH failed_effects AS (
    UPDATE effect_runs SET status = 'failed',
        error = 'build did not succeed', finished_at = now()
    WHERE effect_runs.build_id = $4::bigint
      AND effect_runs.kind = 'push'
      AND effect_runs.status = 'pending'
      AND $1::text IN ('failed', 'cancelled')
)
UPDATE builds
SET status = $1,
    -- Every run starts at pending. Drop the previous attempt's
    -- error, warnings, job set and duration.
    error = CASE
        WHEN $1 = 'pending' THEN NULL
        ELSE COALESCE($2, error)
    END,
    eval_duration_ms = CASE
        WHEN $1 = 'pending' THEN NULL ELSE eval_duration_ms
    END,
    eval_warnings = CASE
        WHEN $1 = 'pending' THEN NULL ELSE eval_warnings
    END,
    eval_completed = CASE
        WHEN $1 = 'pending' THEN FALSE ELSE eval_completed
    END,
    started_at = CASE
        WHEN $1 = 'pending' THEN NULL
        WHEN started_at IS NULL
            AND $1 IN ('evaluating', 'building') THEN now()
        ELSE started_at
    END,
    -- Invariant: non-terminal states never carry finished_at, else
    -- reruns show negative durations.
    finished_at = CASE
        WHEN $1 = ANY($3::text[]) THEN now()
        ELSE NULL
    END
WHERE builds.id = $4::bigint
"""

FIND_COMPLETED_EVAL: typing.Final[str] = """-- name: FindCompletedEval :one
SELECT id FROM builds WHERE project_id = $1 AND tree_hash = $2
AND eval_completed AND id <> $3
ORDER BY id DESC LIMIT 1
"""

EVAL_JOB_ROWS: typing.Final[str] = """-- name: EvalJobRows :many
SELECT attr, system, drv_path, outputs FROM build_attributes
WHERE build_id = $1
"""

GET_BUILD: typing.Final[str] = """-- name: GetBuild :one
SELECT id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_duration_ms, actor, merged_pr_number FROM builds WHERE id = $1
"""

MARK_EFFECTS_STARTED: typing.Final[str] = """-- name: MarkEffectsStarted :one
UPDATE builds SET effects_started = TRUE,
    effects_commit_sha = $1::text,
    effects_branch = $2::text,
    effects_pr_number = $3::bigint
WHERE id = $4::bigint AND effects_started = FALSE RETURNING id
"""

SETTLE_UNFINISHED_ATTRIBUTES: typing.Final[str] = """-- name: SettleUnfinishedAttributes :exec
UPDATE build_attributes
SET status = 'cancelled', finished_at = now()
WHERE build_id = $1 AND status IN ('pending', 'building')
"""

MARK_ATTRIBUTE_BUILDING: typing.Final[str] = """-- name: MarkAttributeBuilding :one
INSERT INTO build_attributes
    (build_id, attr, system, drv_path, status, started_at)
VALUES ($1, $2, $3, $4, 'building', now())
ON CONFLICT (build_id, attr) DO UPDATE SET
    status = 'building',
    started_at = now(),
    finished_at = NULL
WHERE build_attributes.status IN ('pending', 'building')
RETURNING attr
"""

COMPLETE_ATTRIBUTE: typing.Final[str] = """-- name: CompleteAttribute :exec
INSERT INTO build_attributes
    (build_id, attr, system, drv_path, outputs, status, error,
     cached, log_size, log_truncated, finished_at,
     eval_warnings, eval_wall_ms, eval_alloc_bytes)
VALUES ($1, $2, $3, $4, $8::jsonb, $5, $6, $7,
        $9::bigint, $10::boolean, now(),
        $11::jsonb, $12::int,
        $13::bigint)
ON CONFLICT (build_id, attr) DO UPDATE SET
    status = EXCLUDED.status,
    -- Eval data is only known by failed_eval inserts. Build
    -- completions pass NULL and must keep what the eval recorded.
    eval_warnings = COALESCE(EXCLUDED.eval_warnings, build_attributes.eval_warnings),
    eval_wall_ms = COALESCE(EXCLUDED.eval_wall_ms, build_attributes.eval_wall_ms),
    eval_alloc_bytes = COALESCE(EXCLUDED.eval_alloc_bytes, build_attributes.eval_alloc_bytes),
    -- Eval recorded the full outputs map (multi-output drvs);
    -- merge the freshly-known "out" path into it instead of
    -- replacing it, and never NULL an existing map when no out
    -- path is known.
    outputs = CASE
        WHEN EXCLUDED.outputs IS NULL
            THEN build_attributes.outputs
        ELSE COALESCE(build_attributes.outputs, '{}'::jsonb)
            || EXCLUDED.outputs
    END,
    error = EXCLUDED.error,
    cached = EXCLUDED.cached,
    log_size = EXCLUDED.log_size,
    log_truncated = EXCLUDED.log_truncated,
    finished_at = now()
WHERE NOT $14::boolean
    OR build_attributes.status IN ('pending', 'building')
"""

START_EFFECT: typing.Final[str] = """-- name: StartEffect :one
INSERT INTO effect_runs (project_id, kind, build_id, name, status)
SELECT b.project_id, $1::text, b.id, $2::text,
       $3::text
FROM builds b WHERE b.id = $4::bigint
ON CONFLICT (build_id, kind, name) DO UPDATE SET
    status = EXCLUDED.status, error = NULL, log_size = 0,
    log_truncated = FALSE, started_at = now(), finished_at = NULL
RETURNING id
"""

START_PENDING_EFFECTS: typing.Final[str] = """-- name: StartPendingEffects :exec
INSERT INTO effect_runs (project_id, kind, build_id, name, status, deps)
SELECT b.project_id, 'push', b.id, u.name, 'pending', u.deps::jsonb
FROM builds b,
     (SELECT unnest($1::text[]) AS name,
             unnest($2::text[]) AS deps) AS u
WHERE b.id = $3::bigint
ON CONFLICT (build_id, kind, name) DO UPDATE SET
    status = 'pending', error = NULL, log_size = 0,
    log_truncated = FALSE, started_at = now(), finished_at = NULL,
    deps = EXCLUDED.deps
"""

RECORD_SKIPPED_EFFECTS: typing.Final[str] = """-- name: RecordSkippedEffects :exec
INSERT INTO effect_runs (project_id, kind, build_id, name, status, finished_at)
SELECT b.project_id, 'push', b.id, u.name, 'skipped', now()
FROM builds b, unnest($1::text[]) AS u(name)
WHERE b.id = $2::bigint
ON CONFLICT (build_id, kind, name) DO NOTHING
"""

EFFECT_DEP_STATUSES: typing.Final[str] = """-- name: EffectDepStatuses :many
SELECT d.name, d.status FROM effect_runs e
JOIN effect_runs d ON d.build_id = e.build_id AND d.kind = 'push'
    AND d.name IN (SELECT jsonb_array_elements_text(e.deps))
WHERE e.build_id = $1 AND e.kind = 'push' AND e.name = $2
"""

FINISH_EFFECT: typing.Final[str] = """-- name: FinishEffect :exec
UPDATE effect_runs SET
    status = $1, error = $2,
    log_size = $3, log_truncated = $4,
    finished_at = now()
WHERE build_id = $5 AND kind = $6 AND name = $7
"""

EFFECTS_SUMMARY: typing.Final[str] = """-- name: EffectsSummary :one
SELECT
    count(*) FILTER (WHERE status IN ('failed', 'dependency_failed'))::bigint AS failed,
    count(*) FILTER (WHERE status = 'succeeded')::bigint AS succeeded,
    CASE
        WHEN bool_or(status = 'running')
          OR (bool_or(status = 'pending') AND NOT bool_and(status = 'pending'))
          THEN 'running'
        WHEN bool_or(status IN ('failed', 'dependency_failed')) THEN 'failed'
        WHEN bool_or(status = 'pending') THEN 'pending'
        WHEN bool_or(status = 'succeeded') THEN 'succeeded'
        ELSE 'skipped'
    END::text AS status
FROM effect_runs WHERE build_id = $1 AND kind = 'push'
HAVING count(*) > 0
"""

EFFECTS_FOR_BUILD: typing.Final[str] = """-- name: EffectsForBuild :many
SELECT id, project_id, kind, build_id, schedule_name, name, status, error, deps, log_size, log_truncated, started_at, finished_at, payload, code_rev, skip_reason, actor FROM effect_runs WHERE build_id = $1 ORDER BY name
"""

ATTRIBUTE_STATUSES: typing.Final[str] = """-- name: AttributeStatuses :many
SELECT attr, status FROM build_attributes WHERE build_id = $1
"""

LOCK_BUILD_ROW: typing.Final[str] = """-- name: LockBuildRow :one
SELECT id, status, status_generation FROM builds WHERE id = $1 FOR UPDATE
"""

ATTRIBUTE_STATUS_LIST: typing.Final[str] = """-- name: AttributeStatusList :many
SELECT status FROM build_attributes WHERE build_id = $1
"""

BUMP_BUILD_STATUS: typing.Final[str] = """-- name: BumpBuildStatus :one
UPDATE builds
SET status = $2,
    status_generation = status_generation + 1,
    finished_at = COALESCE(finished_at, now())
WHERE id = $1
RETURNING status_generation
"""


class QueryResults[T]:
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]

        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def lock_build_identity(conn: ConnectionLike, *, key: str) -> None:
    await conn.execute(LOCK_BUILD_IDENTITY, key)


async def find_reusable_build(conn: ConnectionLike, *, project_id: int, tree_hash: str | None) -> models.Build | None:
    row = await conn.fetchrow(FIND_REUSABLE_BUILD, project_id, tree_hash)
    if row is None:
        return None
    return models.Build(
        id_=row[0],
        project_id=row[1],
        number=row[2],
        tree_hash=row[3],
        commit_sha=row[4],
        branch=row[5],
        pr_number=row[6],
        pr_author=row[7],
        status=row[8],
        status_generation=row[9],
        effects_started=row[10],
        error=row[11],
        created_at=row[12],
        started_at=row[13],
        finished_at=row[14],
        eval_warnings=row[15],
        eval_completed=row[16],
        effects_commit_sha=row[17],
        effects_branch=row[18],
        effects_pr_number=row[19],
        eval_duration_ms=row[20],
        actor=row[21],
        merged_pr_number=row[22],
    )


async def detach_build_from_pr(conn: ConnectionLike, *, id_: int, pr_number: int | None, branch: str) -> models.Build | None:
    row = await conn.fetchrow(DETACH_BUILD_FROM_PR, id_, pr_number, branch)
    if row is None:
        return None
    return models.Build(
        id_=row[0],
        project_id=row[1],
        number=row[2],
        tree_hash=row[3],
        commit_sha=row[4],
        branch=row[5],
        pr_number=row[6],
        pr_author=row[7],
        status=row[8],
        status_generation=row[9],
        effects_started=row[10],
        error=row[11],
        created_at=row[12],
        started_at=row[13],
        finished_at=row[14],
        eval_warnings=row[15],
        eval_completed=row[16],
        effects_commit_sha=row[17],
        effects_branch=row[18],
        effects_pr_number=row[19],
        eval_duration_ms=row[20],
        actor=row[21],
        merged_pr_number=row[22],
    )


async def attach_build_to_pr(conn: ConnectionLike, *, id_: int, pr_number: int | None, pr_author: str | None) -> models.Build | None:
    row = await conn.fetchrow(ATTACH_BUILD_TO_PR, id_, pr_number, pr_author)
    if row is None:
        return None
    return models.Build(
        id_=row[0],
        project_id=row[1],
        number=row[2],
        tree_hash=row[3],
        commit_sha=row[4],
        branch=row[5],
        pr_number=row[6],
        pr_author=row[7],
        status=row[8],
        status_generation=row[9],
        effects_started=row[10],
        error=row[11],
        created_at=row[12],
        started_at=row[13],
        finished_at=row[14],
        eval_warnings=row[15],
        eval_completed=row[16],
        effects_commit_sha=row[17],
        effects_branch=row[18],
        effects_pr_number=row[19],
        eval_duration_ms=row[20],
        actor=row[21],
        merged_pr_number=row[22],
    )


async def backfill_pr_author(conn: ConnectionLike, *, id_: int, pr_author: str | None) -> models.Build | None:
    row = await conn.fetchrow(BACKFILL_PR_AUTHOR, id_, pr_author)
    if row is None:
        return None
    return models.Build(
        id_=row[0],
        project_id=row[1],
        number=row[2],
        tree_hash=row[3],
        commit_sha=row[4],
        branch=row[5],
        pr_number=row[6],
        pr_author=row[7],
        status=row[8],
        status_generation=row[9],
        effects_started=row[10],
        error=row[11],
        created_at=row[12],
        started_at=row[13],
        finished_at=row[14],
        eval_warnings=row[15],
        eval_completed=row[16],
        effects_commit_sha=row[17],
        effects_branch=row[18],
        effects_pr_number=row[19],
        eval_duration_ms=row[20],
        actor=row[21],
        merged_pr_number=row[22],
    )


async def create_build(conn: ConnectionLike, *, project_id: int, tree_hash: str | None, commit_sha: str, branch: str, pr_number: int | None, pr_author: str | None, actor: str | None) -> models.Build | None:
    row = await conn.fetchrow(CREATE_BUILD, project_id, tree_hash, commit_sha, branch, pr_number, pr_author, actor)
    if row is None:
        return None
    return models.Build(
        id_=row[0],
        project_id=row[1],
        number=row[2],
        tree_hash=row[3],
        commit_sha=row[4],
        branch=row[5],
        pr_number=row[6],
        pr_author=row[7],
        status=row[8],
        status_generation=row[9],
        effects_started=row[10],
        error=row[11],
        created_at=row[12],
        started_at=row[13],
        finished_at=row[14],
        eval_warnings=row[15],
        eval_completed=row[16],
        effects_commit_sha=row[17],
        effects_branch=row[18],
        effects_pr_number=row[19],
        eval_duration_ms=row[20],
        actor=row[21],
        merged_pr_number=row[22],
    )


async def create_failed_build(conn: ConnectionLike, *, project_id: int, commit_sha: str, branch: str, pr_number: int | None, pr_author: str | None, error: str | None) -> models.Build | None:
    row = await conn.fetchrow(CREATE_FAILED_BUILD, project_id, commit_sha, branch, pr_number, pr_author, error)
    if row is None:
        return None
    return models.Build(
        id_=row[0],
        project_id=row[1],
        number=row[2],
        tree_hash=row[3],
        commit_sha=row[4],
        branch=row[5],
        pr_number=row[6],
        pr_author=row[7],
        status=row[8],
        status_generation=row[9],
        effects_started=row[10],
        error=row[11],
        created_at=row[12],
        started_at=row[13],
        finished_at=row[14],
        eval_warnings=row[15],
        eval_completed=row[16],
        effects_commit_sha=row[17],
        effects_branch=row[18],
        effects_pr_number=row[19],
        eval_duration_ms=row[20],
        actor=row[21],
        merged_pr_number=row[22],
    )


async def record_attributes(
    conn: ConnectionLike,
    *,
    build_id: int,
    attrs: collections.abc.Sequence[str],
    systems: collections.abc.Sequence[str],
    drv_paths: collections.abc.Sequence[str],
    outputs: collections.abc.Sequence[str],
    eval_warnings: collections.abc.Sequence[str],
    eval_wall_ms: collections.abc.Sequence[int],
    eval_alloc_bytes: collections.abc.Sequence[int],
) -> None:
    await conn.execute(RECORD_ATTRIBUTES, build_id, attrs, systems, drv_paths, outputs, eval_warnings, eval_wall_ms, eval_alloc_bytes)


async def set_eval_warnings(conn: ConnectionLike, *, id_: int, warnings: str) -> None:
    await conn.execute(SET_EVAL_WARNINGS, id_, warnings)


async def set_build_status(conn: ConnectionLike, *, status: str, error: str | None, terminal: collections.abc.Sequence[str], id_: int) -> None:
    await conn.execute(SET_BUILD_STATUS, status, error, terminal, id_)


async def find_completed_eval(conn: ConnectionLike, *, project_id: int, tree_hash: str | None, exclude_build_id: int) -> int | None:
    row = await conn.fetchrow(FIND_COMPLETED_EVAL, project_id, tree_hash, exclude_build_id)
    if row is None:
        return None
    return row[0]


def eval_job_rows(conn: ConnectionLike, *, build_id: int) -> QueryResults[EvalJobRowsRow]:
    def _decode_hook(row: asyncpg.Record) -> EvalJobRowsRow:
        return EvalJobRowsRow(attr=row[0], system=row[1], drv_path=row[2], outputs=row[3])

    return QueryResults(conn, EVAL_JOB_ROWS, _decode_hook, build_id)


async def get_build(conn: ConnectionLike, *, id_: int) -> models.Build | None:
    row = await conn.fetchrow(GET_BUILD, id_)
    if row is None:
        return None
    return models.Build(
        id_=row[0],
        project_id=row[1],
        number=row[2],
        tree_hash=row[3],
        commit_sha=row[4],
        branch=row[5],
        pr_number=row[6],
        pr_author=row[7],
        status=row[8],
        status_generation=row[9],
        effects_started=row[10],
        error=row[11],
        created_at=row[12],
        started_at=row[13],
        finished_at=row[14],
        eval_warnings=row[15],
        eval_completed=row[16],
        effects_commit_sha=row[17],
        effects_branch=row[18],
        effects_pr_number=row[19],
        eval_duration_ms=row[20],
        actor=row[21],
        merged_pr_number=row[22],
    )


async def mark_effects_started(conn: ConnectionLike, *, commit_sha: str, branch: str, pr_number: int | None, id_: int) -> int | None:
    row = await conn.fetchrow(MARK_EFFECTS_STARTED, commit_sha, branch, pr_number, id_)
    if row is None:
        return None
    return row[0]


async def settle_unfinished_attributes(conn: ConnectionLike, *, build_id: int) -> None:
    await conn.execute(SETTLE_UNFINISHED_ATTRIBUTES, build_id)


async def mark_attribute_building(conn: ConnectionLike, *, build_id: int, attr: str, system: str | None, drv_path: str | None) -> str | None:
    row = await conn.fetchrow(MARK_ATTRIBUTE_BUILDING, build_id, attr, system, drv_path)
    if row is None:
        return None
    return row[0]


async def complete_attribute(
    conn: ConnectionLike,
    *,
    build_id: int,
    attr: str,
    system: str | None,
    drv_path: str | None,
    status: str,
    error: str | None,
    cached: bool,
    outputs: str | None,
    log_size: int,
    log_truncated: bool,
    eval_warnings: str | None,
    eval_wall_ms: int | None,
    eval_alloc_bytes: int | None,
    if_unfinished: bool,
) -> None:
    await conn.execute(COMPLETE_ATTRIBUTE, build_id, attr, system, drv_path, status, error, cached, outputs, log_size, log_truncated, eval_warnings, eval_wall_ms, eval_alloc_bytes, if_unfinished)


async def start_effect(conn: ConnectionLike, *, kind: str, name: str, status: str, build_id: int) -> int | None:
    row = await conn.fetchrow(START_EFFECT, kind, name, status, build_id)
    if row is None:
        return None
    return row[0]


async def start_pending_effects(conn: ConnectionLike, *, names: collections.abc.Sequence[str], deps: collections.abc.Sequence[str], build_id: int) -> None:
    await conn.execute(START_PENDING_EFFECTS, names, deps, build_id)


async def record_skipped_effects(conn: ConnectionLike, *, names: collections.abc.Sequence[str], build_id: int) -> None:
    await conn.execute(RECORD_SKIPPED_EFFECTS, names, build_id)


def effect_dep_statuses(conn: ConnectionLike, *, build_id: int | None, name: str) -> QueryResults[EffectDepStatusesRow]:
    def _decode_hook(row: asyncpg.Record) -> EffectDepStatusesRow:
        return EffectDepStatusesRow(name=row[0], status=row[1])

    return QueryResults(conn, EFFECT_DEP_STATUSES, _decode_hook, build_id, name)


async def finish_effect(conn: ConnectionLike, *, status: str, error: str | None, log_size: int, log_truncated: bool, build_id: int | None, kind: str, name: str) -> None:
    await conn.execute(FINISH_EFFECT, status, error, log_size, log_truncated, build_id, kind, name)


async def effects_summary(conn: ConnectionLike, *, build_id: int | None) -> EffectsSummaryRow | None:
    row = await conn.fetchrow(EFFECTS_SUMMARY, build_id)
    if row is None:
        return None
    return EffectsSummaryRow(failed=row[0], succeeded=row[1], status=row[2])


def effects_for_build(conn: ConnectionLike, *, build_id: int | None) -> QueryResults[models.EffectRun]:
    def _decode_hook(row: asyncpg.Record) -> models.EffectRun:
        return models.EffectRun(
            id_=row[0],
            project_id=row[1],
            kind=row[2],
            build_id=row[3],
            schedule_name=row[4],
            name=row[5],
            status=row[6],
            error=row[7],
            deps=row[8],
            log_size=row[9],
            log_truncated=row[10],
            started_at=row[11],
            finished_at=row[12],
            payload=row[13],
            code_rev=row[14],
            skip_reason=row[15],
            actor=row[16],
        )

    return QueryResults(conn, EFFECTS_FOR_BUILD, _decode_hook, build_id)


def attribute_statuses(conn: ConnectionLike, *, build_id: int) -> QueryResults[AttributeStatusesRow]:
    def _decode_hook(row: asyncpg.Record) -> AttributeStatusesRow:
        return AttributeStatusesRow(attr=row[0], status=row[1])

    return QueryResults(conn, ATTRIBUTE_STATUSES, _decode_hook, build_id)


async def lock_build_row(conn: ConnectionLike, *, id_: int) -> LockBuildRowRow | None:
    row = await conn.fetchrow(LOCK_BUILD_ROW, id_)
    if row is None:
        return None
    return LockBuildRowRow(id_=row[0], status=row[1], status_generation=row[2])


def attribute_status_list(conn: ConnectionLike, *, build_id: int) -> QueryResults[str]:
    return QueryResults(conn, ATTRIBUTE_STATUS_LIST, operator.itemgetter(0), build_id)


async def bump_build_status(conn: ConnectionLike, *, id_: int, status: str) -> int | None:
    row = await conn.fetchrow(BUMP_BUILD_STATUS, id_, status)
    if row is None:
        return None
    return row[0]
