# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
# source file: events.sql
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "QueryResults",
    "SupersedeEventEffectsRow",
    "failed_attr_names",
    "latest_build_for_pr",
    "previous_finished_status",
    "supersede_event_effects",
    "upsert_event_effect",
)

import dataclasses
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc
    import datetime

    type QueryResultsArgsType = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[QueryResultsArgsType] | None

    type ConnectionLike = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from nixbot.db_gen import models


@dataclasses.dataclass()
class SupersedeEventEffectsRow:
    build_id: int | None
    name: str


UPSERT_EVENT_EFFECT: typing.Final[str] = """-- name: UpsertEventEffect :one

INSERT INTO effect_runs (project_id, kind, build_id, name, status, skip_reason,
                         payload, code_rev, actor, started_at, finished_at)
SELECT b.project_id, $1::text, b.id, $2::text,
       $3::text, $4::text,
       $5::jsonb, $6::text, $7::text,
       now(), CASE WHEN $3::text = 'pending' THEN NULL ELSE now() END
FROM builds b WHERE b.id = $8::bigint
ON CONFLICT (build_id, kind, name) DO UPDATE SET
    status = EXCLUDED.status, skip_reason = EXCLUDED.skip_reason,
    payload = EXCLUDED.payload, code_rev = EXCLUDED.code_rev,
    actor = EXCLUDED.actor, error = NULL, log_size = 0, log_truncated = FALSE,
    started_at = EXCLUDED.started_at, finished_at = EXCLUDED.finished_at
WHERE effect_runs.status NOT IN ('running')
RETURNING id
"""

SUPERSEDE_EVENT_EFFECTS: typing.Final[str] = """-- name: SupersedeEventEffects :many
WITH cancelled AS (
    UPDATE effect_runs SET status = 'cancelled', finished_at = now(),
        error = 'superseded by a newer event'
    WHERE project_id = $2::bigint
      AND kind = $1::text
      AND build_id <> $3::bigint
      AND status = 'pending'
      AND ($4::text IS NULL
           OR payload->>'command' = $4::text)
      AND CASE WHEN $5::bigint IS NULL
          THEN payload->'pullRequest' IS NULL
               AND payload->'build'->>'branch' = $6::text
          ELSE (payload->'pullRequest'->>'number')::bigint = $5::bigint
          END
    RETURNING build_id, name
)
UPDATE work_queue w SET status = 'done', finished_at = now()
FROM cancelled c
WHERE w.kind = 'effect' AND w.status = 'pending'
  AND (w.payload->>'build_id')::bigint = c.build_id
  AND w.payload->>'kind' = $1::text
  AND w.payload->>'name' = c.name
RETURNING c.build_id, c.name
"""

LATEST_BUILD_FOR_PR: typing.Final[str] = """-- name: LatestBuildForPr :one
SELECT id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_duration_ms, actor, merged_pr_number FROM builds
WHERE project_id = $1
  AND $2::bigint IN (pr_number, merged_pr_number)
ORDER BY number DESC LIMIT 1
"""

PREVIOUS_FINISHED_STATUS: typing.Final[str] = """-- name: PreviousFinishedStatus :one
SELECT p.status FROM builds b
JOIN builds p ON p.project_id = b.project_id AND p.number < b.number
  AND p.branch = b.branch AND p.pr_number IS NOT DISTINCT FROM b.pr_number
  AND p.status IN ('succeeded', 'failed')
WHERE b.id = $1::bigint
ORDER BY p.number DESC LIMIT 1
"""

FAILED_ATTR_NAMES: typing.Final[str] = """-- name: FailedAttrNames :many
SELECT attr FROM build_attributes
WHERE build_id = $1
  AND status IN ('failed', 'failed_eval', 'dependency_failed', 'cached_failure')
ORDER BY attr LIMIT 50
"""


class QueryResults[T]:
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]

        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


async def upsert_event_effect(conn: ConnectionLike, *, kind: str, name: str, status: str, skip_reason: str | None, payload: str, code_rev: str, actor: str | None, build_id: int) -> int | None:
    row = await conn.fetchrow(UPSERT_EVENT_EFFECT, kind, name, status, skip_reason, payload, code_rev, actor, build_id)
    if row is None:
        return None
    return row[0]


def supersede_event_effects(conn: ConnectionLike, *, kind: str, project_id: int, build_id: int, command: str | None, pr_number: int | None, branch: str | None) -> QueryResults[SupersedeEventEffectsRow]:
    def _decode_hook(row: asyncpg.Record) -> SupersedeEventEffectsRow:
        return SupersedeEventEffectsRow(build_id=row[0], name=row[1])

    return QueryResults(conn, SUPERSEDE_EVENT_EFFECTS, _decode_hook, kind, project_id, build_id, command, pr_number, branch)


async def latest_build_for_pr(conn: ConnectionLike, *, project_id: int, pr_number: int) -> models.Build | None:
    row = await conn.fetchrow(LATEST_BUILD_FOR_PR, project_id, pr_number)
    if row is None:
        return None
    return models.Build(
        id_=row[0],
        project_id=row[1],
        number=row[2],
        tree_hash=row[3],
        commit_sha=row[4],
        branch=row[5],
        pr_number=row[6],
        pr_author=row[7],
        status=row[8],
        status_generation=row[9],
        effects_started=row[10],
        error=row[11],
        created_at=row[12],
        started_at=row[13],
        finished_at=row[14],
        eval_warnings=row[15],
        eval_completed=row[16],
        effects_commit_sha=row[17],
        effects_branch=row[18],
        effects_pr_number=row[19],
        eval_duration_ms=row[20],
        actor=row[21],
        merged_pr_number=row[22],
    )


async def previous_finished_status(conn: ConnectionLike, *, build_id: int) -> str | None:
    row = await conn.fetchrow(PREVIOUS_FINISHED_STATUS, build_id)
    if row is None:
        return None
    return row[0]


def failed_attr_names(conn: ConnectionLike, *, build_id: int) -> QueryResults[str]:
    return QueryResults(conn, FAILED_ATTR_NAMES, operator.itemgetter(0), build_id)
