# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "Build",
    "BuildAttribute",
    "EffectEvalError",
    "EffectRun",
    "Project",
    "ScheduledEffect",
)

import dataclasses
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import datetime
    import uuid


@dataclasses.dataclass()
class Build:
    id_: int
    project_id: int
    number: int
    tree_hash: str | None
    commit_sha: str
    branch: str
    pr_number: int | None
    pr_author: str | None
    status: str
    status_generation: int
    effects_started: bool
    error: str | None
    created_at: datetime.datetime
    started_at: datetime.datetime | None
    finished_at: datetime.datetime | None
    eval_warnings: str | None
    eval_completed: bool
    effects_commit_sha: str | None
    effects_branch: str | None
    effects_pr_number: int | None
    eval_duration_ms: int | None
    actor: str | None
    merged_pr_number: int | None


@dataclasses.dataclass()
class BuildAttribute:
    id_: int
    build_id: int
    attr: str
    system: str | None
    drv_path: str | None
    outputs: str | None
    status: str
    cached: bool
    error: str | None
    started_at: datetime.datetime | None
    finished_at: datetime.datetime | None
    log_size: int
    log_truncated: bool
    eval_warnings: str | None
    eval_wall_ms: int | None
    eval_alloc_bytes: int | None


@dataclasses.dataclass()
class EffectEvalError:
    build_id: int
    source: str
    error: str
    code_rev: str | None
    created_at: datetime.datetime


@dataclasses.dataclass()
class EffectRun:
    id_: int
    project_id: int
    kind: str
    owner: str
    build_id: int | None
    schedule_name: str | None
    name: str
    status: str
    error: str | None
    deps: str | None
    log_size: int
    log_truncated: bool
    started_at: datetime.datetime
    finished_at: datetime.datetime | None
    payload: str | None
    code_rev: str | None
    skip_reason: str | None
    actor: str | None
    lock: str | None


@dataclasses.dataclass()
class Project:
    id_: int
    forge: str
    forge_repo_id: str
    owner: str
    name: str
    default_branch: str
    url: str
    private: bool
    enabled: bool
    next_build_number: int
    created_at: datetime.datetime
    updated_at: datetime.datetime
    reconcile_watermark: datetime.datetime | None
    badge_token: uuid.UUID


@dataclasses.dataclass()
class ScheduledEffect:
    project_id: int
    schedule_name: str
    effect: str
    when_spec: str
    last_run: datetime.datetime | None
