# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
# source file: uploads.sql
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "PendingUploadPathsRow",
    "QueryResults",
    "delete_upload_paths",
    "drop_unknown_uploaders",
    "enqueue_upload_paths",
    "pending_upload_paths",
    "retry_upload_paths",
)

import dataclasses
import operator
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc

    type QueryResultsArgsType = int | float | str | memoryview | collections.abc.Sequence[QueryResultsArgsType] | None

    type ConnectionLike = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]


@dataclasses.dataclass()
class PendingUploadPathsRow:
    id_: int
    path: str
    attempts: int


ENQUEUE_UPLOAD_PATHS: typing.Final[str] = """-- name: EnqueueUploadPaths :many

INSERT INTO upload_queue (uploader, path)
SELECT $1::text, unnest($2::text[])
RETURNING id
"""

PENDING_UPLOAD_PATHS: typing.Final[str] = """-- name: PendingUploadPaths :many
SELECT id, path, attempts FROM upload_queue
WHERE uploader = $1
ORDER BY id
LIMIT $2
"""

DELETE_UPLOAD_PATHS: typing.Final[str] = """-- name: DeleteUploadPaths :exec
DELETE FROM upload_queue WHERE id = ANY($1::bigint[])
"""

RETRY_UPLOAD_PATHS: typing.Final[str] = """-- name: RetryUploadPaths :exec
WITH dropped AS (
    DELETE FROM upload_queue
    WHERE id = ANY($1::bigint[])
      AND attempts + 1 >= $2::int
)
UPDATE upload_queue SET attempts = attempts + 1
WHERE id = ANY($1::bigint[])
  AND attempts + 1 < $2::int
"""

DROP_UNKNOWN_UPLOADERS: typing.Final[str] = """-- name: DropUnknownUploaders :exec
DELETE FROM upload_queue WHERE NOT (uploader = ANY($1::text[]))
"""


class QueryResults[T]:
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]

        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


def enqueue_upload_paths(conn: ConnectionLike, *, uploader: str, paths: collections.abc.Sequence[str]) -> QueryResults[int]:
    return QueryResults(conn, ENQUEUE_UPLOAD_PATHS, operator.itemgetter(0), uploader, paths)


def pending_upload_paths(conn: ConnectionLike, *, uploader: str, limit: int) -> QueryResults[PendingUploadPathsRow]:
    def _decode_hook(row: asyncpg.Record) -> PendingUploadPathsRow:
        return PendingUploadPathsRow(id_=row[0], path=row[1], attempts=row[2])

    return QueryResults(conn, PENDING_UPLOAD_PATHS, _decode_hook, uploader, limit)


async def delete_upload_paths(conn: ConnectionLike, *, ids: collections.abc.Sequence[int]) -> None:
    await conn.execute(DELETE_UPLOAD_PATHS, ids)


async def retry_upload_paths(conn: ConnectionLike, *, ids: collections.abc.Sequence[int], max_attempts: int) -> None:
    await conn.execute(RETRY_UPLOAD_PATHS, ids, max_attempts)


async def drop_unknown_uploaders(conn: ConnectionLike, *, names: collections.abc.Sequence[str]) -> None:
    await conn.execute(DROP_UNKNOWN_UPLOADERS, names)
