# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
# source file: web.sql
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "MetricsAttributeCountsRow",
    "MetricsBuildCountsRow",
    "MetricsBuildDurationRow",
    "MetricsEvalDurationRow",
    "MetricsProjectsRow",
    "QueryResults",
    "WebAttributeCountsRow",
    "WebAttributeHistoryRow",
    "WebAttributeNeighborNumbersRow",
    "WebNeighborNumbersRow",
    "WebQueueRow",
    "WebRecentBuildsRow",
    "WebRepoOverviewRow",
    "attribute_error",
    "attribute_status",
    "metrics_attribute_counts",
    "metrics_build_counts",
    "metrics_build_duration",
    "metrics_eval_duration",
    "metrics_projects",
    "metrics_queue_depth",
    "web_attribute_counts",
    "web_attribute_history",
    "web_attribute_neighbor_numbers",
    "web_attribute_page",
    "web_attributes",
    "web_attributes_finished_after",
    "web_build_by_number",
    "web_builds_for_repo",
    "web_effects",
    "web_neighbor_numbers",
    "web_projects",
    "web_queue",
    "web_recent_builds",
    "web_repo",
    "web_repo_candidates",
    "web_repo_overview",
)

import dataclasses
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import asyncpg.cursor
    import collections.abc
    import datetime

    type QueryResultsArgsType = int | float | str | memoryview | datetime.date | datetime.time | datetime.datetime | datetime.timedelta | collections.abc.Sequence[QueryResultsArgsType] | None

    type ConnectionLike = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]

from nixbot.db_gen import models


@dataclasses.dataclass()
class WebRepoOverviewRow:
    id_: int
    forge: str
    forge_repo_id: str
    owner: str
    name: str
    default_branch: str
    url: str
    private: bool
    enabled: bool
    next_build_number: int
    created_at: datetime.datetime
    updated_at: datetime.datetime
    reconcile_watermark: datetime.datetime | None
    last_number: int
    last_status: str
    last_branch: str
    last_created_at: datetime.datetime
    started_at: datetime.datetime | None
    finished_at: datetime.datetime | None
    history: str
    median_secs: float
    pass_rate: int


@dataclasses.dataclass()
class WebRecentBuildsRow:
    id_: int
    project_id: int
    number: int
    tree_hash: str | None
    commit_sha: str
    branch: str
    pr_number: int | None
    pr_author: str | None
    status: str
    status_generation: int
    effects_started: bool
    error: str | None
    created_at: datetime.datetime
    started_at: datetime.datetime | None
    finished_at: datetime.datetime | None
    eval_warnings: str | None
    eval_completed: bool
    effects_commit_sha: str | None
    effects_branch: str | None
    effects_pr_number: int | None
    eval_duration_ms: int | None
    owner: str
    project_name: str
    forge: str
    url: str


@dataclasses.dataclass()
class WebNeighborNumbersRow:
    prev: int
    next: int


@dataclasses.dataclass()
class WebAttributeCountsRow:
    status: str
    count: int
    warned: int


@dataclasses.dataclass()
class WebAttributeHistoryRow:
    id_: int
    build_id: int
    attr: str
    system: str | None
    drv_path: str | None
    outputs: str | None
    status: str
    cached: bool
    error: str | None
    started_at: datetime.datetime | None
    finished_at: datetime.datetime | None
    log_size: int
    log_truncated: bool
    eval_warnings: str | None
    eval_wall_ms: int | None
    eval_alloc_bytes: int | None
    build_number: int
    branch: str
    commit_sha: str
    build_created_at: datetime.datetime


@dataclasses.dataclass()
class WebAttributeNeighborNumbersRow:
    prev: int
    next: int


@dataclasses.dataclass()
class WebQueueRow:
    id_: int
    project_id: int
    number: int
    tree_hash: str | None
    commit_sha: str
    branch: str
    pr_number: int | None
    pr_author: str | None
    status: str
    status_generation: int
    effects_started: bool
    error: str | None
    created_at: datetime.datetime
    started_at: datetime.datetime | None
    finished_at: datetime.datetime | None
    eval_warnings: str | None
    eval_completed: bool
    effects_commit_sha: str | None
    effects_branch: str | None
    effects_pr_number: int | None
    eval_duration_ms: int | None
    owner: str
    project_name: str
    forge: str
    url: str
    queue_position: int


@dataclasses.dataclass()
class MetricsBuildCountsRow:
    status: str
    count: int


@dataclasses.dataclass()
class MetricsAttributeCountsRow:
    status: str
    count: int


@dataclasses.dataclass()
class MetricsBuildDurationRow:
    total: float
    count: int


@dataclasses.dataclass()
class MetricsProjectsRow:
    enabled: int
    total: int


@dataclasses.dataclass()
class MetricsEvalDurationRow:
    total: int
    count: int


WEB_PROJECTS: typing.Final[str] = """-- name: WebProjects :many

SELECT id, forge, forge_repo_id, owner, name, default_branch, url, private, enabled, next_build_number, created_at, updated_at, reconcile_watermark FROM projects
WHERE ($1::boolean IS NULL OR enabled = $1)
  AND ($2::text IS NULL OR owner || '/' || name ILIKE $2)
ORDER BY owner, name
"""

WEB_REPO: typing.Final[str] = """-- name: WebRepo :one
SELECT id, forge, forge_repo_id, owner, name, default_branch, url, private, enabled, next_build_number, created_at, updated_at, reconcile_watermark FROM projects WHERE forge = $1 AND owner = $2 AND name = $3
"""

WEB_REPO_CANDIDATES: typing.Final[str] = """-- name: WebRepoCandidates :many
SELECT id, forge, forge_repo_id, owner, name, default_branch, url, private, enabled, next_build_number, created_at, updated_at, reconcile_watermark FROM projects WHERE owner = $1 AND name = $2
ORDER BY forge, id
"""

WEB_REPO_OVERVIEW: typing.Final[str] = """-- name: WebRepoOverview :many
SELECT p.id, p.forge, p.forge_repo_id, p.owner, p.name, p.default_branch, p.url, p.private, p.enabled, p.next_build_number, p.created_at, p.updated_at, p.reconcile_watermark,
       lb.number AS last_number, lb.status AS last_status,
       lb.branch AS last_branch, lb.created_at AS last_created_at,
       lb.started_at, lb.finished_at,
       h.history, m.median_secs, m.pass_rate
FROM projects p
LEFT JOIN LATERAL (
    SELECT id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_duration_ms FROM builds b WHERE b.project_id = p.id
      AND b.pr_number IS NULL AND b.branch = p.default_branch
    ORDER BY b.number DESC LIMIT 1
) lb ON true
LEFT JOIN LATERAL (
    SELECT json_agg(
        json_build_object(
            'number', t.number, 'status', t.status,
            'secs', EXTRACT(EPOCH FROM (t.finished_at - t.started_at))
        )
        ORDER BY t.number
    ) AS history
    FROM (
        SELECT number, status, started_at, finished_at FROM builds b
        WHERE b.project_id = p.id
          AND b.pr_number IS NULL AND b.branch = p.default_branch
        ORDER BY number DESC LIMIT 10
    ) t
) h ON true
LEFT JOIN LATERAL (
    -- Median, not mean: one build stuck behind a busy nix daemon must
    -- not dominate the typical duration.
    SELECT percentile_cont(0.5) WITHIN GROUP (
               ORDER BY EXTRACT(EPOCH FROM (t.finished_at - t.started_at))
           ) FILTER (WHERE t.status = 'succeeded') AS median_secs,
           -- Cancelled builds say nothing about the code: they must
           -- not drag the pass rate toward zero.
           count(*) FILTER (WHERE t.status = 'succeeded')::float
               / NULLIF(
                   count(*) FILTER (
                       WHERE t.status IN ('succeeded', 'failed')
                   ), 0) AS pass_rate
    FROM (
        SELECT status, started_at, finished_at FROM builds b
        WHERE b.project_id = p.id
          AND b.pr_number IS NULL AND b.branch = p.default_branch
          AND b.status IN ('succeeded', 'failed', 'cancelled')
        ORDER BY b.number DESC LIMIT 30
    ) t
) m ON true
WHERE p.enabled AND ($1::bigint[] IS NULL OR p.id = ANY($1))
  AND ($2::text IS NULL OR p.owner || '/' || p.name ILIKE $2)
ORDER BY p.owner, p.name
"""

WEB_RECENT_BUILDS: typing.Final[str] = """-- name: WebRecentBuilds :many
SELECT b.id, b.project_id, b.number, b.tree_hash, b.commit_sha, b.branch, b.pr_number, b.pr_author, b.status, b.status_generation, b.effects_started, b.error, b.created_at, b.started_at, b.finished_at, b.eval_warnings, b.eval_completed, b.effects_commit_sha, b.effects_branch, b.effects_pr_number, b.eval_duration_ms, p.owner, p.name AS project_name, p.forge, p.url
FROM builds b JOIN projects p ON p.id = b.project_id
WHERE ($1::bigint[] IS NULL OR b.project_id = ANY($1))
  AND ($2::bigint IS NULL OR b.id < $2)
ORDER BY b.id DESC LIMIT $3::bigint
"""

WEB_BUILDS_FOR_REPO: typing.Final[str] = """-- name: WebBuildsForRepo :many
SELECT id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_duration_ms FROM builds
WHERE project_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR branch = $3)
  AND ($4::int IS NULL OR pr_number = $4)
  AND ($5::text IS NULL
       OR starts_with(commit_sha, $5))
  AND ($6::bigint IS NULL OR id < $6)
ORDER BY number DESC LIMIT $8 OFFSET $7
"""

WEB_BUILD_BY_NUMBER: typing.Final[str] = """-- name: WebBuildByNumber :one
SELECT id, project_id, number, tree_hash, commit_sha, branch, pr_number, pr_author, status, status_generation, effects_started, error, created_at, started_at, finished_at, eval_warnings, eval_completed, effects_commit_sha, effects_branch, effects_pr_number, eval_duration_ms FROM builds WHERE project_id = $1 AND number = $2
"""

WEB_NEIGHBOR_NUMBERS: typing.Final[str] = """-- name: WebNeighborNumbers :one
SELECT (max(number) FILTER (WHERE number < $2))::bigint AS prev,
       (min(number) FILTER (WHERE number > $2))::bigint AS next
FROM builds WHERE project_id = $1
"""

WEB_ATTRIBUTES: typing.Final[str] = """-- name: WebAttributes :many
SELECT a.id, a.build_id, a.attr, a.system, a.drv_path, a.outputs, a.status, a.cached, a.error, a.started_at, a.finished_at, a.log_size, a.log_truncated, a.eval_warnings, a.eval_wall_ms, a.eval_alloc_bytes FROM build_attributes a
WHERE a.build_id = $1
ORDER BY CASE
    WHEN a.status IN ('failed', 'failed_eval', 'dependency_failed',
                      'cached_failure') THEN 0
    WHEN a.status = 'building' THEN 1
    WHEN a.status = 'pending' THEN 2
    WHEN a.status = 'cancelled' THEN 3
    ELSE 4
END, a.attr
"""

WEB_ATTRIBUTES_FINISHED_AFTER: typing.Final[str] = """-- name: WebAttributesFinishedAfter :many
SELECT a.id, a.build_id, a.attr, a.system, a.drv_path, a.outputs, a.status, a.cached, a.error, a.started_at, a.finished_at, a.log_size, a.log_truncated, a.eval_warnings, a.eval_wall_ms, a.eval_alloc_bytes FROM build_attributes a
WHERE a.build_id = $1 AND a.finished_at IS NOT NULL
  AND ($2::timestamptz IS NULL
       OR (a.finished_at, a.id) > ($2::timestamptz,
                                   $3::bigint))
ORDER BY a.finished_at, a.id
"""

WEB_EFFECTS: typing.Final[str] = """-- name: WebEffects :many
SELECT id, build_id, name, status, error, log_size, log_truncated, started_at, finished_at, deps FROM build_effects WHERE build_id = $1
ORDER BY array_position(
    ARRAY['failed', 'dependency_failed', 'running', 'pending', 'succeeded', 'skipped'],
    status), name
"""

WEB_ATTRIBUTE_COUNTS: typing.Final[str] = """-- name: WebAttributeCounts :many
SELECT status, count(*) AS count,
       count(*) FILTER (WHERE eval_warnings IS NOT NULL) AS warned
FROM build_attributes
WHERE build_id = $1 AND ($2::text IS NULL OR attr ILIKE $2)
GROUP BY status
"""

WEB_ATTRIBUTE_PAGE: typing.Final[str] = """-- name: WebAttributePage :many
SELECT a.id, a.build_id, a.attr, a.system, a.drv_path, a.outputs, a.status, a.cached, a.error, a.started_at, a.finished_at, a.log_size, a.log_truncated, a.eval_warnings, a.eval_wall_ms, a.eval_alloc_bytes FROM build_attributes a
WHERE a.build_id = $1 AND a.status = ANY($2::text[])
  AND ($3::text IS NULL OR a.attr ILIKE $3)
ORDER BY (a.eval_warnings IS NULL), a.attr
LIMIT $5::bigint OFFSET $4::bigint
"""

WEB_ATTRIBUTE_HISTORY: typing.Final[str] = """-- name: WebAttributeHistory :many
SELECT a.id, a.build_id, a.attr, a.system, a.drv_path, a.outputs, a.status, a.cached, a.error, a.started_at, a.finished_at, a.log_size, a.log_truncated, a.eval_warnings, a.eval_wall_ms, a.eval_alloc_bytes, b.number AS build_number, b.branch, b.commit_sha,
       b.created_at AS build_created_at
FROM build_attributes a
JOIN builds b ON b.id = a.build_id
WHERE b.project_id = $1 AND a.attr = $2
ORDER BY b.number DESC LIMIT $3::bigint
"""

WEB_ATTRIBUTE_NEIGHBOR_NUMBERS: typing.Final[str] = """-- name: WebAttributeNeighborNumbers :one
SELECT (max(b.number) FILTER (WHERE b.number < $3))::bigint AS prev,
       (min(b.number) FILTER (WHERE b.number > $3))::bigint AS next
FROM build_attributes a
JOIN builds b ON b.id = a.build_id
WHERE b.project_id = $1 AND a.attr = $2
"""

WEB_QUEUE: typing.Final[str] = """-- name: WebQueue :many
SELECT b.id, b.project_id, b.number, b.tree_hash, b.commit_sha, b.branch, b.pr_number, b.pr_author, b.status, b.status_generation, b.effects_started, b.error, b.created_at, b.started_at, b.finished_at, b.eval_warnings, b.eval_completed, b.effects_commit_sha, b.effects_branch, b.effects_pr_number, b.eval_duration_ms, p.owner, p.name AS project_name, p.forge, p.url,
       q.queue_position
FROM builds b
JOIN projects p ON p.id = b.project_id
LEFT JOIN (
    SELECT id, row_number() OVER (ORDER BY id) AS queue_position
    FROM builds WHERE status = 'pending'
) q ON q.id = b.id
WHERE b.status IN ('pending', 'evaluating', 'building')
  AND ($1::bigint[] IS NULL OR p.id = ANY($1))
ORDER BY b.status = 'pending', b.id
"""

ATTRIBUTE_STATUS: typing.Final[str] = """-- name: AttributeStatus :one
SELECT status FROM build_attributes WHERE build_id = $1 AND attr = $2
"""

ATTRIBUTE_ERROR: typing.Final[str] = """-- name: AttributeError :one
SELECT error FROM build_attributes WHERE build_id = $1 AND attr = $2
"""

METRICS_BUILD_COUNTS: typing.Final[str] = """-- name: MetricsBuildCounts :many
SELECT status, count(*) AS count FROM builds GROUP BY status
"""

METRICS_ATTRIBUTE_COUNTS: typing.Final[str] = """-- name: MetricsAttributeCounts :many
SELECT status, count(*) AS count FROM build_attributes GROUP BY status
"""

METRICS_QUEUE_DEPTH: typing.Final[str] = """-- name: MetricsQueueDepth :one
SELECT count(*) AS count FROM builds
WHERE status IN ('pending', 'evaluating', 'building')
"""

METRICS_BUILD_DURATION: typing.Final[str] = """-- name: MetricsBuildDuration :one
SELECT
    coalesce(sum(extract(epoch FROM finished_at - started_at)), 0)::float AS total,
    count(*) AS count
FROM builds
WHERE started_at IS NOT NULL AND finished_at IS NOT NULL
"""

METRICS_PROJECTS: typing.Final[str] = """-- name: MetricsProjects :one
SELECT count(*) FILTER (WHERE enabled) AS enabled, count(*) AS total
FROM projects
"""

METRICS_EVAL_DURATION: typing.Final[str] = """-- name: MetricsEvalDuration :one
SELECT coalesce(sum(eval_duration_ms), 0)::float / 1000 AS total, count(*) AS count
FROM builds WHERE eval_duration_ms IS NOT NULL
"""


class QueryResults[T]:
    __slots__ = ("_args", "_conn", "_cursor", "_decode_hook", "_iterator", "_sql")

    def __init__(
        self,
        conn: ConnectionLike,
        sql: str,
        decode_hook: collections.abc.Callable[[asyncpg.Record], T],
        *args: QueryResultsArgsType,
    ) -> None:
        self._conn = conn
        self._sql = sql
        self._decode_hook = decode_hook
        self._args = args
        self._cursor: asyncpg.cursor.CursorFactory[asyncpg.Record] | None = None
        self._iterator: asyncpg.cursor.CursorIterator[asyncpg.Record] | None = None

    def __aiter__(self) -> QueryResults[T]:
        return self

    def __await__(
        self,
    ) -> collections.abc.Generator[None, None, collections.abc.Sequence[T]]:
        async def _wrapper() -> collections.abc.Sequence[T]:
            result = await self._conn.fetch(self._sql, *self._args)
            return [self._decode_hook(row) for row in result]

        return _wrapper().__await__()

    async def __anext__(self) -> T:
        if self._cursor is None or self._iterator is None:
            self._cursor = self._conn.cursor(self._sql, *self._args)
            self._iterator = self._cursor.__aiter__()
        try:
            record = await self._iterator.__anext__()
        except StopAsyncIteration:
            self._cursor = None
            self._iterator = None
            raise
        return self._decode_hook(record)


def web_projects(conn: ConnectionLike, *, enabled: bool | None, pattern: str | None) -> QueryResults[models.Project]:
    def _decode_hook(row: asyncpg.Record) -> models.Project:
        return models.Project(id_=row[0], forge=row[1], forge_repo_id=row[2], owner=row[3], name=row[4], default_branch=row[5], url=row[6], private=row[7], enabled=row[8], next_build_number=row[9], created_at=row[10], updated_at=row[11], reconcile_watermark=row[12])

    return QueryResults(conn, WEB_PROJECTS, _decode_hook, enabled, pattern)


async def web_repo(conn: ConnectionLike, *, forge: str, owner: str, name: str) -> models.Project | None:
    row = await conn.fetchrow(WEB_REPO, forge, owner, name)
    if row is None:
        return None
    return models.Project(id_=row[0], forge=row[1], forge_repo_id=row[2], owner=row[3], name=row[4], default_branch=row[5], url=row[6], private=row[7], enabled=row[8], next_build_number=row[9], created_at=row[10], updated_at=row[11], reconcile_watermark=row[12])


def web_repo_candidates(conn: ConnectionLike, *, owner: str, name: str) -> QueryResults[models.Project]:
    def _decode_hook(row: asyncpg.Record) -> models.Project:
        return models.Project(id_=row[0], forge=row[1], forge_repo_id=row[2], owner=row[3], name=row[4], default_branch=row[5], url=row[6], private=row[7], enabled=row[8], next_build_number=row[9], created_at=row[10], updated_at=row[11], reconcile_watermark=row[12])

    return QueryResults(conn, WEB_REPO_CANDIDATES, _decode_hook, owner, name)


def web_repo_overview(conn: ConnectionLike, *, project_ids: collections.abc.Sequence[int] | None, pattern: str | None) -> QueryResults[WebRepoOverviewRow]:
    def _decode_hook(row: asyncpg.Record) -> WebRepoOverviewRow:
        return WebRepoOverviewRow(
            id_=row[0],
            forge=row[1],
            forge_repo_id=row[2],
            owner=row[3],
            name=row[4],
            default_branch=row[5],
            url=row[6],
            private=row[7],
            enabled=row[8],
            next_build_number=row[9],
            created_at=row[10],
            updated_at=row[11],
            reconcile_watermark=row[12],
            last_number=row[13],
            last_status=row[14],
            last_branch=row[15],
            last_created_at=row[16],
            started_at=row[17],
            finished_at=row[18],
            history=row[19],
            median_secs=row[20],
            pass_rate=row[21],
        )

    return QueryResults(conn, WEB_REPO_OVERVIEW, _decode_hook, project_ids, pattern)


def web_recent_builds(conn: ConnectionLike, *, project_ids: collections.abc.Sequence[int] | None, before: int | None, limit_: int) -> QueryResults[WebRecentBuildsRow]:
    def _decode_hook(row: asyncpg.Record) -> WebRecentBuildsRow:
        return WebRecentBuildsRow(
            id_=row[0],
            project_id=row[1],
            number=row[2],
            tree_hash=row[3],
            commit_sha=row[4],
            branch=row[5],
            pr_number=row[6],
            pr_author=row[7],
            status=row[8],
            status_generation=row[9],
            effects_started=row[10],
            error=row[11],
            created_at=row[12],
            started_at=row[13],
            finished_at=row[14],
            eval_warnings=row[15],
            eval_completed=row[16],
            effects_commit_sha=row[17],
            effects_branch=row[18],
            effects_pr_number=row[19],
            eval_duration_ms=row[20],
            owner=row[21],
            project_name=row[22],
            forge=row[23],
            url=row[24],
        )

    return QueryResults(conn, WEB_RECENT_BUILDS, _decode_hook, project_ids, before, limit_)


def web_builds_for_repo(conn: ConnectionLike, *, project_id: int, status: str | None, branch: str | None, pr_number: int | None, commit_prefix: str | None, before: int | None, offset: int, limit: int) -> QueryResults[models.Build]:
    def _decode_hook(row: asyncpg.Record) -> models.Build:
        return models.Build(
            id_=row[0],
            project_id=row[1],
            number=row[2],
            tree_hash=row[3],
            commit_sha=row[4],
            branch=row[5],
            pr_number=row[6],
            pr_author=row[7],
            status=row[8],
            status_generation=row[9],
            effects_started=row[10],
            error=row[11],
            created_at=row[12],
            started_at=row[13],
            finished_at=row[14],
            eval_warnings=row[15],
            eval_completed=row[16],
            effects_commit_sha=row[17],
            effects_branch=row[18],
            effects_pr_number=row[19],
            eval_duration_ms=row[20],
        )

    return QueryResults(conn, WEB_BUILDS_FOR_REPO, _decode_hook, project_id, status, branch, pr_number, commit_prefix, before, offset, limit)


async def web_build_by_number(conn: ConnectionLike, *, project_id: int, number: int) -> models.Build | None:
    row = await conn.fetchrow(WEB_BUILD_BY_NUMBER, project_id, number)
    if row is None:
        return None
    return models.Build(
        id_=row[0],
        project_id=row[1],
        number=row[2],
        tree_hash=row[3],
        commit_sha=row[4],
        branch=row[5],
        pr_number=row[6],
        pr_author=row[7],
        status=row[8],
        status_generation=row[9],
        effects_started=row[10],
        error=row[11],
        created_at=row[12],
        started_at=row[13],
        finished_at=row[14],
        eval_warnings=row[15],
        eval_completed=row[16],
        effects_commit_sha=row[17],
        effects_branch=row[18],
        effects_pr_number=row[19],
        eval_duration_ms=row[20],
    )


async def web_neighbor_numbers(conn: ConnectionLike, *, project_id: int, number: int) -> WebNeighborNumbersRow | None:
    row = await conn.fetchrow(WEB_NEIGHBOR_NUMBERS, project_id, number)
    if row is None:
        return None
    return WebNeighborNumbersRow(prev=row[0], next=row[1])


def web_attributes(conn: ConnectionLike, *, build_id: int) -> QueryResults[models.BuildAttribute]:
    def _decode_hook(row: asyncpg.Record) -> models.BuildAttribute:
        return models.BuildAttribute(
            id_=row[0],
            build_id=row[1],
            attr=row[2],
            system=row[3],
            drv_path=row[4],
            outputs=row[5],
            status=row[6],
            cached=row[7],
            error=row[8],
            started_at=row[9],
            finished_at=row[10],
            log_size=row[11],
            log_truncated=row[12],
            eval_warnings=row[13],
            eval_wall_ms=row[14],
            eval_alloc_bytes=row[15],
        )

    return QueryResults(conn, WEB_ATTRIBUTES, _decode_hook, build_id)


def web_attributes_finished_after(conn: ConnectionLike, *, build_id: int, after: datetime.datetime | None, after_id: int) -> QueryResults[models.BuildAttribute]:
    def _decode_hook(row: asyncpg.Record) -> models.BuildAttribute:
        return models.BuildAttribute(
            id_=row[0],
            build_id=row[1],
            attr=row[2],
            system=row[3],
            drv_path=row[4],
            outputs=row[5],
            status=row[6],
            cached=row[7],
            error=row[8],
            started_at=row[9],
            finished_at=row[10],
            log_size=row[11],
            log_truncated=row[12],
            eval_warnings=row[13],
            eval_wall_ms=row[14],
            eval_alloc_bytes=row[15],
        )

    return QueryResults(conn, WEB_ATTRIBUTES_FINISHED_AFTER, _decode_hook, build_id, after, after_id)


def web_effects(conn: ConnectionLike, *, build_id: int) -> QueryResults[models.BuildEffect]:
    def _decode_hook(row: asyncpg.Record) -> models.BuildEffect:
        return models.BuildEffect(id_=row[0], build_id=row[1], name=row[2], status=row[3], error=row[4], log_size=row[5], log_truncated=row[6], started_at=row[7], finished_at=row[8], deps=row[9])

    return QueryResults(conn, WEB_EFFECTS, _decode_hook, build_id)


def web_attribute_counts(conn: ConnectionLike, *, build_id: int, pattern: str | None) -> QueryResults[WebAttributeCountsRow]:
    def _decode_hook(row: asyncpg.Record) -> WebAttributeCountsRow:
        return WebAttributeCountsRow(status=row[0], count=row[1], warned=row[2])

    return QueryResults(conn, WEB_ATTRIBUTE_COUNTS, _decode_hook, build_id, pattern)


def web_attribute_page(conn: ConnectionLike, *, build_id: int, statuses: collections.abc.Sequence[str], pattern: str | None, offset_: int, limit_: int) -> QueryResults[models.BuildAttribute]:
    def _decode_hook(row: asyncpg.Record) -> models.BuildAttribute:
        return models.BuildAttribute(
            id_=row[0],
            build_id=row[1],
            attr=row[2],
            system=row[3],
            drv_path=row[4],
            outputs=row[5],
            status=row[6],
            cached=row[7],
            error=row[8],
            started_at=row[9],
            finished_at=row[10],
            log_size=row[11],
            log_truncated=row[12],
            eval_warnings=row[13],
            eval_wall_ms=row[14],
            eval_alloc_bytes=row[15],
        )

    return QueryResults(conn, WEB_ATTRIBUTE_PAGE, _decode_hook, build_id, statuses, pattern, offset_, limit_)


def web_attribute_history(conn: ConnectionLike, *, project_id: int, attr: str, limit_: int) -> QueryResults[WebAttributeHistoryRow]:
    def _decode_hook(row: asyncpg.Record) -> WebAttributeHistoryRow:
        return WebAttributeHistoryRow(
            id_=row[0],
            build_id=row[1],
            attr=row[2],
            system=row[3],
            drv_path=row[4],
            outputs=row[5],
            status=row[6],
            cached=row[7],
            error=row[8],
            started_at=row[9],
            finished_at=row[10],
            log_size=row[11],
            log_truncated=row[12],
            eval_warnings=row[13],
            eval_wall_ms=row[14],
            eval_alloc_bytes=row[15],
            build_number=row[16],
            branch=row[17],
            commit_sha=row[18],
            build_created_at=row[19],
        )

    return QueryResults(conn, WEB_ATTRIBUTE_HISTORY, _decode_hook, project_id, attr, limit_)


async def web_attribute_neighbor_numbers(conn: ConnectionLike, *, project_id: int, attr: str, build_number: int) -> WebAttributeNeighborNumbersRow | None:
    row = await conn.fetchrow(WEB_ATTRIBUTE_NEIGHBOR_NUMBERS, project_id, attr, build_number)
    if row is None:
        return None
    return WebAttributeNeighborNumbersRow(prev=row[0], next=row[1])


def web_queue(conn: ConnectionLike, *, project_ids: collections.abc.Sequence[int] | None) -> QueryResults[WebQueueRow]:
    def _decode_hook(row: asyncpg.Record) -> WebQueueRow:
        return WebQueueRow(
            id_=row[0],
            project_id=row[1],
            number=row[2],
            tree_hash=row[3],
            commit_sha=row[4],
            branch=row[5],
            pr_number=row[6],
            pr_author=row[7],
            status=row[8],
            status_generation=row[9],
            effects_started=row[10],
            error=row[11],
            created_at=row[12],
            started_at=row[13],
            finished_at=row[14],
            eval_warnings=row[15],
            eval_completed=row[16],
            effects_commit_sha=row[17],
            effects_branch=row[18],
            effects_pr_number=row[19],
            eval_duration_ms=row[20],
            owner=row[21],
            project_name=row[22],
            forge=row[23],
            url=row[24],
            queue_position=row[25],
        )

    return QueryResults(conn, WEB_QUEUE, _decode_hook, project_ids)


async def attribute_status(conn: ConnectionLike, *, build_id: int, attr: str) -> str | None:
    row = await conn.fetchrow(ATTRIBUTE_STATUS, build_id, attr)
    if row is None:
        return None
    return row[0]


async def attribute_error(conn: ConnectionLike, *, build_id: int, attr: str) -> str | None:
    row = await conn.fetchrow(ATTRIBUTE_ERROR, build_id, attr)
    if row is None:
        return None
    return row[0]


def metrics_build_counts(conn: ConnectionLike) -> QueryResults[MetricsBuildCountsRow]:
    def _decode_hook(row: asyncpg.Record) -> MetricsBuildCountsRow:
        return MetricsBuildCountsRow(status=row[0], count=row[1])

    return QueryResults(conn, METRICS_BUILD_COUNTS, _decode_hook)


def metrics_attribute_counts(conn: ConnectionLike) -> QueryResults[MetricsAttributeCountsRow]:
    def _decode_hook(row: asyncpg.Record) -> MetricsAttributeCountsRow:
        return MetricsAttributeCountsRow(status=row[0], count=row[1])

    return QueryResults(conn, METRICS_ATTRIBUTE_COUNTS, _decode_hook)


async def metrics_queue_depth(conn: ConnectionLike) -> int | None:
    row = await conn.fetchrow(METRICS_QUEUE_DEPTH)
    if row is None:
        return None
    return row[0]


async def metrics_build_duration(conn: ConnectionLike) -> MetricsBuildDurationRow | None:
    row = await conn.fetchrow(METRICS_BUILD_DURATION)
    if row is None:
        return None
    return MetricsBuildDurationRow(total=row[0], count=row[1])


async def metrics_projects(conn: ConnectionLike) -> MetricsProjectsRow | None:
    row = await conn.fetchrow(METRICS_PROJECTS)
    if row is None:
        return None
    return MetricsProjectsRow(enabled=row[0], total=row[1])


async def metrics_eval_duration(conn: ConnectionLike) -> MetricsEvalDurationRow | None:
    row = await conn.fetchrow(METRICS_EVAL_DURATION)
    if row is None:
        return None
    return MetricsEvalDurationRow(total=row[0], count=row[1])
