# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.31.1
#   sqlc-gen-better-python v0.9.0
# source file: work_queue.sql
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "ClaimNextWorkItemRow",
    "claim_next_work_item",
    "cleanup_work_queue",
    "enqueue_effect_items",
    "enqueue_work_item",
    "finish_work_item",
    "settle_interrupted_work",
)

import dataclasses
import typing

if typing.TYPE_CHECKING:
    import asyncpg
    import collections.abc

    type ConnectionLike = asyncpg.Connection[asyncpg.Record] | asyncpg.pool.PoolConnectionProxy[asyncpg.Record]


@dataclasses.dataclass()
class ClaimNextWorkItemRow:
    id_: int
    kind: str
    dedup_key: str
    payload: str


ENQUEUE_WORK_ITEM: typing.Final[str] = """-- name: EnqueueWorkItem :one

INSERT INTO work_queue (kind, dedup_key, payload)
VALUES ($1, $2, $3::jsonb)
ON CONFLICT (kind, dedup_key, md5(payload::text))
WHERE status = 'pending'
DO NOTHING
RETURNING id
"""

ENQUEUE_EFFECT_ITEMS: typing.Final[str] = """-- name: EnqueueEffectItems :exec
INSERT INTO work_queue (kind, dedup_key, payload)
SELECT 'effect', u.dedup_key,
       jsonb_build_object('build_id', $1::bigint,
                          'name', u.name)
FROM (SELECT unnest($2::text[]) AS name,
             unnest($3::text[]) AS dedup_key) AS u
ON CONFLICT (kind, dedup_key, md5(payload::text))
WHERE status = 'pending'
DO NOTHING
"""

CLAIM_NEXT_WORK_ITEM: typing.Final[str] = """-- name: ClaimNextWorkItem :one
UPDATE work_queue SET status = 'running', claimed_at = now()
WHERE id = (
    SELECT id FROM work_queue w
    WHERE w.status = 'pending'
      AND NOT EXISTS (
        SELECT 1 FROM work_queue r
        WHERE r.dedup_key = w.dedup_key
          AND (r.status = 'running'
               OR (r.status = 'pending'
                   AND (r.created_at, r.id) < (w.created_at, w.id)))
      )
      AND NOT (w.kind = 'effect' AND EXISTS (
        SELECT 1 FROM build_effects e
        JOIN build_effects d ON d.build_id = e.build_id
            AND d.name IN (SELECT jsonb_array_elements_text(e.deps))
        WHERE e.build_id = (w.payload->>'build_id')::bigint
          AND e.name = w.payload->>'name'
          AND d.status IN ('pending', 'running')
      ))
    ORDER BY w.created_at, w.id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, kind, dedup_key, payload
"""

FINISH_WORK_ITEM: typing.Final[str] = """-- name: FinishWorkItem :exec
UPDATE work_queue
SET status = $2, error = $3, finished_at = now()
WHERE id = $1
"""

SETTLE_INTERRUPTED_WORK: typing.Final[str] = """-- name: SettleInterruptedWork :exec
WITH requeued AS (
    UPDATE work_queue w SET status = 'pending', claimed_at = NULL
    WHERE w.status = 'running' AND NOT EXISTS (
        SELECT 1 FROM work_queue p
        WHERE p.kind = w.kind AND p.dedup_key = w.dedup_key
          AND p.status = 'pending'
    )
)
UPDATE work_queue w SET status = 'failed', finished_at = now(),
    error = 'interrupted; superseded by a newer request'
WHERE w.status = 'running' AND EXISTS (
    SELECT 1 FROM work_queue p
    WHERE p.kind = w.kind AND p.dedup_key = w.dedup_key
      AND p.status = 'pending'
)
"""

CLEANUP_WORK_QUEUE: typing.Final[str] = """-- name: CleanupWorkQueue :exec
DELETE FROM work_queue
WHERE finished_at IS NOT NULL
  AND finished_at < now() - make_interval(days => $1::int)
"""


async def enqueue_work_item(conn: ConnectionLike, *, kind: str, dedup_key: str, payload: str) -> int | None:
    row = await conn.fetchrow(ENQUEUE_WORK_ITEM, kind, dedup_key, payload)
    if row is None:
        return None
    return row[0]


async def enqueue_effect_items(conn: ConnectionLike, *, build_id: int, names: collections.abc.Sequence[str], dedup_keys: collections.abc.Sequence[str]) -> None:
    await conn.execute(ENQUEUE_EFFECT_ITEMS, build_id, names, dedup_keys)


async def claim_next_work_item(conn: ConnectionLike) -> ClaimNextWorkItemRow | None:
    row = await conn.fetchrow(CLAIM_NEXT_WORK_ITEM)
    if row is None:
        return None
    return ClaimNextWorkItemRow(id_=row[0], kind=row[1], dedup_key=row[2], payload=row[3])


async def finish_work_item(conn: ConnectionLike, *, id_: int, status: str, error: str | None) -> None:
    await conn.execute(FINISH_WORK_ITEM, id_, status, error)


async def settle_interrupted_work(conn: ConnectionLike) -> None:
    await conn.execute(SETTLE_INTERRUPTED_WORK)


async def cleanup_work_queue(conn: ConnectionLike, *, retention_days: int) -> None:
    await conn.execute(CLEANUP_WORK_QUEUE, retention_days)
